#############################################################################
# Makefile for building: nutshell
# Generated by qmake (2.01a) (Qt 4.8.3) on: Thu 4. Oct 05:34:28 2012
# Project:  nutshellQt.pro
# Template: app
# Command: c:\Qt\4.8.3vc\bin\qmake.exe -spec c:\Qt\4.8.3vc\mkspecs\win32-msvc2010 CONFIG+=declarative_debug -o Makefile nutshellQt.pro
#############################################################################

first: debug
install: debug-install
uninstall: debug-uninstall
MAKEFILE      = Makefile
QMAKE         = c:\Qt\4.8.3vc\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
SUBTARGETS    =  \
		debug \
		release

debug: $(MAKEFILE).Debug FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_default: $(MAKEFILE).Debug FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug 
debug-make_first: $(MAKEFILE).Debug FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug first
debug-all: $(MAKEFILE).Debug FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: $(MAKEFILE).Debug FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: $(MAKEFILE).Debug FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: $(MAKEFILE).Debug FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: $(MAKEFILE).Debug FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: $(MAKEFILE).Release FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release
release-make_default: $(MAKEFILE).Release FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release 
release-make_first: $(MAKEFILE).Release FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release first
release-all: $(MAKEFILE).Release FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: $(MAKEFILE).Release FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: $(MAKEFILE).Release FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: $(MAKEFILE).Release FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: $(MAKEFILE).Release FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: nutshellQt.pro  c:\Qt\4.8.3vc\mkspecs\win32-msvc2010\qmake.conf c:\Qt\4.8.3vc\mkspecs\qconfig.pri \
		c:\Qt\4.8.3vc\mkspecs\modules\qt_webkit_version.pri \
		c:\Qt\4.8.3vc\mkspecs\features\qt_functions.prf \
		c:\Qt\4.8.3vc\mkspecs\features\qt_config.prf \
		c:\Qt\4.8.3vc\mkspecs\features\exclusive_builds.prf \
		c:\Qt\4.8.3vc\mkspecs\features\default_pre.prf \
		c:\Qt\4.8.3vc\mkspecs\features\win32\default_pre.prf \
		c:\Qt\4.8.3vc\mkspecs\features\debug.prf \
		c:\Qt\4.8.3vc\mkspecs\features\debug_and_release.prf \
		c:\Qt\4.8.3vc\mkspecs\features\default_post.prf \
		c:\Qt\4.8.3vc\mkspecs\features\win32\default_post.prf \
		c:\Qt\4.8.3vc\mkspecs\features\win32\exceptions.prf \
		c:\Qt\4.8.3vc\mkspecs\features\declarative_debug.prf \
		c:\Qt\4.8.3vc\mkspecs\features\win32\rtti.prf \
		c:\Qt\4.8.3vc\mkspecs\features\win32\stl.prf \
		c:\Qt\4.8.3vc\mkspecs\features\shared.prf \
		c:\Qt\4.8.3vc\mkspecs\features\win32\embed_manifest_exe.prf \
		c:\Qt\4.8.3vc\mkspecs\features\win32\embed_manifest_dll.prf \
		c:\Qt\4.8.3vc\mkspecs\features\warn_on.prf \
		c:\Qt\4.8.3vc\mkspecs\features\qt.prf \
		c:\Qt\4.8.3vc\mkspecs\features\win32\thread.prf \
		c:\Qt\4.8.3vc\mkspecs\features\moc.prf \
		c:\Qt\4.8.3vc\mkspecs\features\win32\windows.prf \
		c:\Qt\4.8.3vc\mkspecs\features\resources.prf \
		c:\Qt\4.8.3vc\mkspecs\features\uic.prf \
		c:\Qt\4.8.3vc\mkspecs\features\yacc.prf \
		c:\Qt\4.8.3vc\mkspecs\features\lex.prf \
		c:\Qt\4.8.3vc\lib\qtmaind.prl
	$(QMAKE) -spec c:\Qt\4.8.3vc\mkspecs\win32-msvc2010 CONFIG+=declarative_debug -o Makefile nutshellQt.pro
c:\Qt\4.8.3vc\mkspecs\qconfig.pri:
c:\Qt\4.8.3vc\mkspecs\modules\qt_webkit_version.pri:
c:\Qt\4.8.3vc\mkspecs\features\qt_functions.prf:
c:\Qt\4.8.3vc\mkspecs\features\qt_config.prf:
c:\Qt\4.8.3vc\mkspecs\features\exclusive_builds.prf:
c:\Qt\4.8.3vc\mkspecs\features\default_pre.prf:
c:\Qt\4.8.3vc\mkspecs\features\win32\default_pre.prf:
c:\Qt\4.8.3vc\mkspecs\features\debug.prf:
c:\Qt\4.8.3vc\mkspecs\features\debug_and_release.prf:
c:\Qt\4.8.3vc\mkspecs\features\default_post.prf:
c:\Qt\4.8.3vc\mkspecs\features\win32\default_post.prf:
c:\Qt\4.8.3vc\mkspecs\features\win32\exceptions.prf:
c:\Qt\4.8.3vc\mkspecs\features\declarative_debug.prf:
c:\Qt\4.8.3vc\mkspecs\features\win32\rtti.prf:
c:\Qt\4.8.3vc\mkspecs\features\win32\stl.prf:
c:\Qt\4.8.3vc\mkspecs\features\shared.prf:
c:\Qt\4.8.3vc\mkspecs\features\win32\embed_manifest_exe.prf:
c:\Qt\4.8.3vc\mkspecs\features\win32\embed_manifest_dll.prf:
c:\Qt\4.8.3vc\mkspecs\features\warn_on.prf:
c:\Qt\4.8.3vc\mkspecs\features\qt.prf:
c:\Qt\4.8.3vc\mkspecs\features\win32\thread.prf:
c:\Qt\4.8.3vc\mkspecs\features\moc.prf:
c:\Qt\4.8.3vc\mkspecs\features\win32\windows.prf:
c:\Qt\4.8.3vc\mkspecs\features\resources.prf:
c:\Qt\4.8.3vc\mkspecs\features\uic.prf:
c:\Qt\4.8.3vc\mkspecs\features\yacc.prf:
c:\Qt\4.8.3vc\mkspecs\features\lex.prf:
c:\Qt\4.8.3vc\lib\qtmaind.prl:
qmake: qmake_all FORCE
	@$(QMAKE) -spec c:\Qt\4.8.3vc\mkspecs\win32-msvc2010 CONFIG+=declarative_debug -o Makefile nutshellQt.pro

qmake_all: FORCE

make_default: debug-make_default release-make_default FORCE
make_first: debug-make_first release-make_first FORCE
all: debug-all release-all FORCE
clean: debug-clean release-clean FORCE
	-$(DEL_FILE) "debug\objs\nutshell.intermediate.manifest"
	-$(DEL_FILE) debug\objs\nutshell_pch.pch
	-$(DEL_FILE) debug\vc\nutshell.exp
	-$(DEL_FILE) debug\vc\nutshell.ilk
	-$(DEL_FILE) vc*.pdb
	-$(DEL_FILE) vc*.idb
distclean: debug-distclean release-distclean FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) debug\vc\nutshell.pdb

check: first

debug-mocclean: $(MAKEFILE).Debug
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean: $(MAKEFILE).Release
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables: $(MAKEFILE).Debug
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables: $(MAKEFILE).Release
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
